Feature/cambio consecutivo
udistrital/necesidades_crud pull request #52
Opened 2022-02-09 18:41 UTC by DanKazuky

https://github.com/udistrital/necesidades_cliente/issues/318

2022-02-10 04:19 UTC, AlexFBP requested changes

2022-02-10 04:19 UTC, AlexFBP commented on database/migrations/20220208_232314_necesidad.go
> +}
- Revisar: Esta migración falló probando en local
![image](https://user-images.githubusercontent.com/6588872/153336042-cb083aa1-8f2a-42dc-aa9b-9f5e6056f2a7.png)
- El `EXEC` está sospechoso... Revisar [otras alternativas](https://www.postgresqltutorial.com/postgresql-rename-column/)
- En el `Down()` posiblemente falta `COLUMN` después de `ADD`? ([Referencia](https://www.postgresqltutorial.com/postgresql-add-column/))
- En general en las migraciones, el rollback (`Down()`) debe hacerse inverso y coherente con la migración, por ejemplo, si lo último que se hizo en una migración (`Up()`) fue agregar una columna, lo primero que deberá hacerse en el rollback (`Down()`) deberá ser eliminar dicha columna

2022-02-11 04:33 UTC, DanKazuky commented on database/migrations/20220208_232314_necesidad.go
> +}
Corregido

2022-02-15 02:38 UTC, AlexFBP approved these changes

2022-02-15 02:42 UTC, merged